
export const PATHS = {
    ROOT: '/',
    DASHBOARD: '/dashboard',
    ANALYTIC: '/analytic',
    ORGANIZATION: '/organization',
    DEPARTMENTS: '/departments',
    LIST_DEPARTMENTS: '/department/departments',
    CREATE_DEPARTMENT: '/department/departments/create',
    IMPORT_DEPARTMENTS: '/department/departments/import',
    BRANCHES: '/branches',
    LIST_BRANCHES: '/department/branches',
    CREATE_BRANCH: '/department/branches/create',
    IMPORT_BRANCHES: '/department/branches/import',
    EMPLOYEES: '/employees',
    EMPLOYEES_ID: (id: string = ':id') => `/employees/${id}`,
    CREATE_EMPLOYEE: '/employees/create',
    IMPORT_EMPLOYEES: '/employees/import',
    ROLES: '/roles',
    ROLES_ID: (id: string = ':id') => `/roles/${id}`,
    CREATE_ROLE: '/roles/create',
    CLASSROOMS: '/class-room',
    CREATE_CLASSROOM: '/class-room/create',
}